### ISSUE TITLE
[feature]: table row actions

### ISSUE THREAD

**Issue by casperiv0** [Dev-CasperTheGhost/home-inventory#26]
**Please describe your wanted feature**
Able to select table rows and delete selected rows.

## todo

- [x] add `bulk-delete` endpoint to `products`
- [x] add `bulkDelete(productIds[])` to redux actions
- [x] add  deletion handler for table
- [x] look into possible mem leak when deleting all products
